### ISSUE TITLE
Inconsistent use of "a" and "rdf:type"

### ISSUE THREAD

**Issue by mhoangvslev** [hobbit-project/hobbit-project.github.io#7]
I recommend the consistent use of "rdf:type" in the .nt files instead of mixing "rdf:type" and "a".

**Comment by MichaelRoeder** [comment]
Which file are you referring to?

**Comment by mhoangvslev** [comment]
I was referring to all Abox, Tbox files

**Comment by MichaelRoeder** [comment]
This project is about the documentation of the HOBBIT project. This project supports a lot of benchmarks and systems. Hence, I would suggest that you are more precise what exactly you refer to.

However, the usage of `a` and `rdf:type` means that the `nt` files you have are in the [turtle format](https://www.w3.org/TR/turtle/). When you look into the W3C reference, you will find the following sentence: 
```
The token 'a' in the predicate position of a Turtle triple represents the IRI http://www.w3.org/1999/02/22-rdf-syntax-ns#type .
```
From this sentence, it follows that `a` can be used to replace `rdf:type` but it doesn't have to be used. Hence, from the point of view of the serialization, it is not an error.
